"""init

Revision ID: b9a9ebe8b08d
Revises:
Create Date: 2026-04-15 12:16:57.610919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9a9ebe8b08d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum("student", "counselor", "admin", "system", name="user_role"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="user_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("actor_role", sa.String(length=50), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "performed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_performed_at"), "audit_logs", ["performed_at"], unique=False
    )
    op.create_table(
        "counselor_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("max_slots_day", sa.Integer(), nullable=False),
        sa.Column(
            "max_active_cases", sa.Integer(), nullable=False, server_default="10"
        ),
        sa.Column(
            "current_active_cases", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "working_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_counselor_profiles_user_id"),
        "counselor_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "FCM", "IN_APP", name="notification_channel"),
            nullable=False,
        ),
        sa.Column("template_code", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="notification_status"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_status"), "notifications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "student_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("college_id", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("consent_flag", sa.Boolean(), nullable=False),
        sa.Column("consent_version", sa.String(length=20), nullable=True),
        sa.Column("consents", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "profile_status",
            sa.Enum(
                "PENDING_CONSENT", "ACTIVE", "INACTIVE", name="student_profile_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "guardian_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_profiles_college_id"),
        "student_profiles",
        ["college_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_student_profiles_user_id"),
        "student_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("counselor_id", sa.String(length=36), nullable=False),
        sa.Column("priority_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("slot_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_RANKING",
                "ASSIGNED",
                "CONFIRMED",
                "DECLINED",
                "EXPIRED",
                "RELEASED",
                "REASSIGNED",
                "COMPLETED",
                name="allocation_status",
            ),
            nullable=False,
        ),
        sa.Column("reason_summary", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["counselor_id"],
            ["counselor_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["student_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_allocations_counselor_id"),
        "allocations",
        ["counselor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_allocations_status"), "allocations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_allocations_student_id"), "allocations", ["student_id"], unique=False
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column(
            "assessment_type",
            sa.Enum("INITIAL", "PERIODIC", "POST_SESSION", name="assessment_type"),
            nullable=False,
        ),
        sa.Column(
            "phq9_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("phq9_total", sa.Integer(), nullable=False),
        sa.Column(
            "gad7_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("gad7_total", sa.Integer(), nullable=False),
        sa.Column("q9_flag", sa.Boolean(), nullable=False),
        sa.Column("sleep_score", sa.Integer(), nullable=False),
        sa.Column("academic_stress_score", sa.Integer(), nullable=False),
        sa.Column(
            "social_isolation_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="isolation_level"),
            nullable=False,
        ),
        sa.Column(
            "risk_processing_status",
            sa.Enum("PENDING", "DONE", name="risk_processing_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["student_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_student_id"), "assessments", ["student_id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("allocation_id", sa.String(length=36), nullable=False),
        sa.Column("sender_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"], ["allocations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_allocation_id"),
        "chat_messages",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_created_at"),
        "chat_messages",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "risk_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("cri_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("GREEN", "YELLOW", "RED", name="risk_level"),
            nullable=False,
        ),
        sa.Column("reasoning", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "trend",
            sa.Enum("IMPROVING", "STABLE", "WORSENING", name="risk_trend"),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum("ASSESSMENT_SUBMITTED", "PERIODIC_RECOMPUTE", name="risk_trigger"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["student_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_logs_created_at"), "risk_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_risk_logs_student_id"), "risk_logs", ["student_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("allocation_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CONFIRMED",
                "IN_PROGRESS",
                "COMPLETED",
                "MISSED",
                "CANCELLED",
                name="session_status",
            ),
            nullable=False,
        ),
        sa.Column("session_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_allocation_id"), "sessions", ["allocation_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_table(
        "session_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("counselor_id", sa.String(length=36), nullable=False),
        sa.Column(
            "mood", sa.Enum("LOW", "NEUTRAL", "HIGH", name="note_mood"), nullable=False
        ),
        sa.Column(
            "engagement",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="note_engagement"),
            nullable=False,
        ),
        sa.Column("key_concerns", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "risk_flag",
            sa.Enum("IMPROVING", "STABLE", "WORSENING", name="note_risk_flag"),
            nullable=False,
        ),
        sa.Column("action_plan", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["counselor_id"],
            ["counselor_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_notes_session_id"),
        "session_notes",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_notes_session_id"), table_name="session_notes")
    op.drop_table("session_notes")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_allocation_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_risk_logs_student_id"), table_name="risk_logs")
    op.drop_index(op.f("ix_risk_logs_created_at"), table_name="risk_logs")
    op.drop_table("risk_logs")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_allocation_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_assessments_student_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_allocations_student_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_status"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_counselor_id"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_student_profiles_user_id"), table_name="student_profiles")
    op.drop_index(op.f("ix_student_profiles_college_id"), table_name="student_profiles")
    op.drop_table("student_profiles")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_counselor_profiles_user_id"), table_name="counselor_profiles"
    )
    op.drop_table("counselor_profiles")
    op.drop_index(op.f("ix_audit_logs_performed_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
