"""add google oauth support to users

Revision ID: e2289f7a1f4c
Revises: f1e2d3c4b5a6
Create Date: 2026-04-22 12:49:45.548402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2289f7a1f4c'
down_revision: Union[str, Sequence[str], None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add Google OAuth columns
    op.add_column('users', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    
    # Make password_hash nullable for OAuth users
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=512),
               nullable=True)
    
    # Add unique constraint for google_id
    op.create_unique_constraint('uq_user_google_id', 'users', ['google_id'])
    
    # Fix the missing foreign key in user_roles (detected by autogenerate)
    # op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###
